language: python
python:
  - "2.7"
  - "3.5"


before_install:
  - pip install coveralls
  - pip install coverage>=4.2
  - pip install pytest

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install .

# command to run tests
script:
  - pytest

# safelist
branches:
  only:
  - master
  - travis

after_success:
  - pip install .
  - coverage run --source=connect4/ -m pytest
  - coveralls
